version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - connfd
  - desctiptor
  - Florian
  - glog
  - Grisu
  - iovcnt
  - lmit
  - Loitsch
  - optlen
  - peeraddr
  - pidbuf
  - sshthresh
  - SYSFATAL
  - unrecovered
  - VALGRIND
  - zonefile
ignoreWords: []
import: []
