version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - connfd
  - desctiptor
  - EPOLLERR
  - epollfd
  - EPOLLHUP
  - EPOLLIN
  - EPOLLOUT
  - EPOLLPRI
  - EPOLLRDHUP
  - eventfd
  - Eventfd
  - eventloop
  - extrabuf
  - Florian
  - glog
  - Grisu
  - iovcnt
  - lmit
  - Loitsch
  - optlen
  - peeraddr
  - pidbuf
  - prependable
  - sshthresh
  - SYSFATAL
  - timerfd
  - unrecovered
  - unwrite
  - VALGRIND
  - zonefile
ignoreWords: []
import: []
